import { Injectable } from '@angular/core';
import { GoogleGenAI } from '@google/genai';

// This is a placeholder for the API key.
// In the Applet environment, process.env.API_KEY is set.
declare var process: any;

@Injectable({
  providedIn: 'root',
})
export class GeminiService {
  private ai: GoogleGenAI | null = null;

  constructor() {
    try {
      if (typeof process !== 'undefined' && process.env && process.env.API_KEY) {
        this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      } else {
        console.error('API_KEY environment variable not found.');
      }
    } catch (e) {
      console.error('Error initializing GoogleGenAI:', e);
    }
  }

  async generateBannerImage(
    prompt: string,
    aspectRatio: '1:1' | '16:9' | '4:3' | '3:4' | '9:16'
  ): Promise<string> {
    if (!this.ai) {
      throw new Error('Gemini AI client is not initialized. Check API Key.');
    }

    try {
      const response = await this.ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: aspectRatio,
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
        return `data:image/jpeg;base64,${base64ImageBytes}`;
      } else {
        throw new Error('No images were generated by the API.');
      }
    } catch (error) {
      console.error('Error generating image with Gemini:', error);
      if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
      }
      throw new Error('An unknown error occurred while generating the image.');
    }
  }
}
